"""expand_inbound_and_add_batch_lot

Revision ID: 1d9c4afb64af
Revises: 7a3c4aece2c6
Create Date: 2026-05-13 18:22:04.275197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9c4afb64af'
down_revision: Union[str, Sequence[str], None] = '7a3c4aece2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_lots',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manufacturing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_lots_product_batch', 'batch_lots', ['product_id', 'batch_number'], unique=True)
    op.add_column('inbound_items', sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('inbound_items', sa.Column('match_metadata', sa.JSON(), nullable=True))
    op.add_column('inbound_sessions', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('inbound_sessions', sa.Column('supplier_id', sa.Uuid(), nullable=True))
    op.add_column('inbound_sessions', sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('inbound_sessions', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('inbound_sessions', sa.Column('request_number', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'inbound_sessions', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbound_sessions', type_='foreignkey')
    op.drop_column('inbound_sessions', 'request_number')
    op.drop_column('inbound_sessions', 'contract_number')
    op.drop_column('inbound_sessions', 'total_value')
    op.drop_column('inbound_sessions', 'supplier_id')
    op.drop_column('inbound_sessions', 'document_type')
    op.drop_column('inbound_items', 'match_metadata')
    op.drop_column('inbound_items', 'match_score')
    op.drop_index('ix_batch_lots_product_batch', table_name='batch_lots')
    op.drop_table('batch_lots')
    # ### end Alembic commands ###
