"""expand_supplier_and_manufacturer

Revision ID: 6549d5db422a
Revises: 1d9c4afb64af
Create Date: 2026-05-13 18:26:37.595408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6549d5db422a'
down_revision: Union[str, Sequence[str], None] = '1d9c4afb64af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('external_id', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('contract_number', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('contract_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('suppliers', sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'contract_value')
    op.drop_column('suppliers', 'contract_date')
    op.drop_column('suppliers', 'contract_number')
    op.drop_column('suppliers', 'external_id')
    op.drop_column('manufacturers', 'external_id')
    # ### end Alembic commands ###
