"""add_sticky_context_to_user

Revision ID: 6aea32c4cc6a
Revises: 8ce8e799dfb2
Create Date: 2026-05-13 16:27:33.737223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aea32c4cc6a'
down_revision: Union[str, Sequence[str], None] = '8ce8e799dfb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active_unit_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('last_active_sector_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'units', ['last_active_unit_id'], ['id'])
    op.create_foreign_key(None, 'users', 'sectors', ['last_active_sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_active_sector_id')
    op.drop_column('users', 'last_active_unit_id')
    # ### end Alembic commands ###
