"""separate_business_and_integration_states

Revision ID: 74754f158641
Revises: ab7aeba598b6
Create Date: 2026-05-13 17:06:49.640405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74754f158641'
down_revision: Union[str, Sequence[str], None] = 'ab7aeba598b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'PENDING_REVIEW', name='business_status_enum').create(op.get_bind())
    sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='integration_status_enum').create(op.get_bind())
    
    op.add_column('products', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'PENDING_REVIEW', name='business_status_enum'), server_default='PENDING_REVIEW', nullable=False))
    op.add_column('products', sa.Column('integration_status', sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='integration_status_enum'), server_default='PENDING', nullable=False))
    op.drop_column('products', 'registration_status')
    
    # Drop old enum
    sa.Enum(name='registration_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='registration_status_enum').create(op.get_bind())
    
    op.add_column('products', sa.Column('registration_status', postgresql.ENUM('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='registration_status_enum'), server_default=sa.text("'PENDING'::registration_status_enum"), autoincrement=False, nullable=False))
    op.drop_column('products', 'integration_status')
    op.drop_column('products', 'status')
    
    sa.Enum(name='integration_status_enum').drop(op.get_bind())
    sa.Enum(name='business_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
