"""add_metadata_to_context_switch_logs

Revision ID: 8ce8e799dfb2
Revises: ed6694dc03ed
Create Date: 2026-05-13 15:25:28.419275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8e799dfb2'
down_revision: Union[str, Sequence[str], None] = 'ed6694dc03ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_switch_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('context_switch_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('context_switch_logs', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_switch_logs', 'correlation_id')
    op.drop_column('context_switch_logs', 'user_agent')
    op.drop_column('context_switch_logs', 'ip_address')
    # ### end Alembic commands ###
