"""refine_catalog_models_with_erp_refs

Revision ID: a57f00fc11c1
Revises: 6aea32c4cc6a
Create Date: 2026-05-13 16:48:20.571129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57f00fc11c1'
down_revision: Union[str, Sequence[str], None] = '6aea32c4cc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_ingredients', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('active_ingredients', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('active_ingredients', sa.Column('external_code', sa.String(length=50), nullable=True))
    op.add_column('active_ingredients', sa.Column('pharmaceutical_form_id', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('active_ingredients_name_key'), 'active_ingredients', type_='unique')
    op.create_foreign_key(None, 'active_ingredients', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.add_column('products', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('external_code', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('group_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('subgroup_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'subgroup_id')
    op.drop_column('products', 'group_id')
    op.drop_column('products', 'external_code')
    op.drop_column('products', 'external_id')
    op.drop_constraint(None, 'active_ingredients', type_='foreignkey')
    op.create_unique_constraint(op.f('active_ingredients_name_key'), 'active_ingredients', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('active_ingredients', 'pharmaceutical_form_id')
    op.drop_column('active_ingredients', 'external_code')
    op.drop_column('active_ingredients', 'external_id')
    op.drop_column('active_ingredients', 'tenant_id')
    # ### end Alembic commands ###
