"""sanitary_safety_and_drift

Revision ID: ab2f91267393
Revises: 554620416a24
Create Date: 2026-05-13 18:50:52.963551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab2f91267393'
down_revision: Union[str, Sequence[str], None] = '554620416a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_items', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('inbound_items', sa.Column('reconciliation_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.add_column('inbound_items', sa.Column('confirmation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('inbound_items', 'match_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('inventory_balances', sa.Column('erp_synced_balance', sa.Numeric(precision=15, scale=4), server_default='0.0000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_balances', 'erp_synced_balance')
    op.alter_column('inbound_items', 'match_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('inbound_items', 'confirmation_metadata')
    op.drop_column('inbound_items', 'reconciliation_history')
    op.drop_column('inbound_items', 'is_blocked')
    # ### end Alembic commands ###
