"""add_registration_status_to_product

Revision ID: ab7aeba598b6
Revises: a57f00fc11c1
Create Date: 2026-05-13 16:52:13.511845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7aeba598b6'
down_revision: Union[str, Sequence[str], None] = 'a57f00fc11c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='registration_status_enum').create(op.get_bind())
    op.add_column('products', sa.Column('registration_status', sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='registration_status_enum'), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'registration_status')
    sa.Enum('PENDING', 'PRINCIPLE_SYNCED', 'PRODUCT_SYNCED', 'LINKED', 'COMPLETED', 'FAILED', name='registration_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
