"""add_internal_code_and_sequences

Revision ID: abc16df5618a
Revises: 67cd813f36f3
Create Date: 2026-05-13 14:40:11.500312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc16df5618a'
down_revision: Union[str, Sequence[str], None] = '67cd813f36f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_sequences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('start_range', sa.Integer(), server_default='1000000', nullable=False),
    sa.Column('current_value', sa.Integer(), server_default='1000000', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('internal_code', sa.Integer(), nullable=True))
    op.create_index('ix_products_internal_code', 'products', ['internal_code'], unique=False)
    op.create_unique_constraint(None, 'products', ['internal_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index('ix_products_internal_code', table_name='products')
    op.drop_column('products', 'internal_code')
    op.drop_table('code_sequences')
    # ### end Alembic commands ###
