"""create_integration_logs_table

Revision ID: bb72e2cc63e1
Revises: 74754f158641
Create Date: 2026-05-13 17:19:09.461208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb72e2cc63e1'
down_revision: Union[str, Sequence[str], None] = '74754f158641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('intent_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'RETRY', name='integration_step_status_enum'), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_intent_id'), 'integration_logs', ['intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_logs_intent_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    sa.Enum('SUCCESS', 'FAILURE', 'RETRY', name='integration_step_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
