"""retrofit_operational_entities_with_context

Revision ID: bbd1d5f4604c
Revises: abc16df5618a
Create Date: 2026-05-13 14:46:54.740211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd1d5f4604c'
down_revision: Union[str, Sequence[str], None] = 'abc16df5618a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movements', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('inventory_movements', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'inventory_movements', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'inventory_movements', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    op.add_column('products', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'products', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'products', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'unit_id')
    op.drop_column('products', 'tenant_id')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_column('inventory_movements', 'unit_id')
    op.drop_column('inventory_movements', 'tenant_id')
    # ### end Alembic commands ###
