"""add_drift_watermark

Revision ID: bfdcacccfda7
Revises: b3a7c8d9e0f1
Create Date: 2026-05-13 19:14:25.740593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdcacccfda7'
down_revision: Union[str, Sequence[str], None] = 'b3a7c8d9e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_balances', sa.Column('last_synced_movement_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'inventory_balances', 'inventory_movements', ['last_synced_movement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_balances', type_='foreignkey')
    op.drop_column('inventory_balances', 'last_synced_movement_id')
    # ### end Alembic commands ###
