"""retrofit_ingestion_with_operational_context

Revision ID: c02b1ec02a9d
Revises: d100c5d25d6d
Create Date: 2026-05-13 15:09:01.057525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02b1ec02a9d'
down_revision: Union[str, Sequence[str], None] = 'd100c5d25d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_sessions', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('import_sessions', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.add_column('import_sessions', sa.Column('target_sector_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'import_sessions', 'tenants', ['tenant_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'import_sessions', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'import_sessions', 'sectors', ['target_sector_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_sessions', type_='foreignkey')
    op.drop_constraint(None, 'import_sessions', type_='foreignkey')
    op.drop_constraint(None, 'import_sessions', type_='foreignkey')
    op.drop_column('import_sessions', 'target_sector_id')
    op.drop_column('import_sessions', 'unit_id')
    op.drop_column('import_sessions', 'tenant_id')
    # ### end Alembic commands ###
