"""create_products_table

Revision ID: c33455aec7a0
Revises: b0dde1ed3951
Create Date: 2026-05-13 11:14:41.555489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33455aec7a0'
down_revision: Union[str, Sequence[str], None] = 'b0dde1ed3951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('ean', sa.String(length=13), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit_of_measure', sa.Enum('UNIT', 'BOX', 'BOTTLE', 'AMPOULE', name='unit_of_measure_enum'), nullable=False),
    sa.Column('stock_current', sa.Numeric(precision=15, scale=4), server_default='0.0000', nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=15, scale=4), server_default='0.0000', nullable=False),
    sa.Column('active_ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_ingredient_id'], ['active_ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean'),
    sa.UniqueConstraint('sku')
    )
    
    # Operational Indexes (Requirement 8)
    op.create_index('ix_products_sku', 'products', ['sku'])
    op.create_index('ix_products_ean', 'products', ['ean'])
    op.create_index('ix_products_name', 'products', ['name'])
    op.create_index('ix_products_deleted_at', 'products', ['deleted_at'])

    # Apply trigger for updated_at
    op.execute("""
        CREATE TRIGGER update_products_updated_at
        BEFORE UPDATE ON products
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_products_updated_at ON products")
    op.drop_index('ix_products_deleted_at', table_name='products')
    op.drop_index('ix_products_name', table_name='products')
    op.drop_index('ix_products_ean', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
