"""create_ingestion_tables

Revision ID: c870d022d462
Revises: c93b16d9daaa
Create Date: 2026-05-13 12:03:06.493109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c870d022d462'
down_revision: Union[str, Sequence[str], None] = 'c93b16d9daaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATED', 'COMPLETED', 'FAILED', 'ABORTED', name='ingestion_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_staging',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('product_exists', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('active_ingredient_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Apply trigger for updated_at on import_sessions
    op.execute("""
        CREATE TRIGGER update_import_sessions_updated_at
        BEFORE UPDATE ON import_sessions
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_import_sessions_updated_at ON import_sessions")
    op.drop_table('import_staging')
    op.drop_table('import_sessions')
    # ### end Alembic commands ###
