"""decouple_catalog_and_stock_adr_011

Revision ID: d100c5d25d6d
Revises: bbd1d5f4604c
Create Date: 2026-05-13 14:58:23.376637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd100c5d25d6d'
down_revision: Union[str, Sequence[str], None] = 'bbd1d5f4604c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_balances',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=4), server_default='0.0000', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_balance_lookup', 'inventory_balances', ['product_id', 'unit_id', 'sector_id'], unique=True)
    op.create_index('ix_inv_balance_tenant', 'inventory_balances', ['tenant_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('sector_id', sa.Uuid(), nullable=True))
    op.create_index('ix_inventory_movements_sector_id', 'inventory_movements', ['sector_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'sectors', ['sector_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('products_unit_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'unit_id')
    op.drop_column('products', 'stock_current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_current', sa.NUMERIC(precision=15, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_unit_id_fkey'), 'products', 'units', ['unit_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index('ix_inventory_movements_sector_id', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'sector_id')
    op.drop_index('ix_inv_balance_tenant', table_name='inventory_balances')
    op.drop_index('ix_inv_balance_lookup', table_name='inventory_balances')
    op.drop_table('inventory_balances')
    # ### end Alembic commands ###
