"""add_forensic_fields_to_integration_logs

Revision ID: d2a1c62fc854
Revises: bb72e2cc63e1
Create Date: 2026-05-13 17:38:14.438726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a1c62fc854'
down_revision: Union[str, Sequence[str], None] = 'bb72e2cc63e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('TIMEOUT', 'VALIDATION', 'AUTH', 'ERP_ERROR', 'UNKNOWN', name='failure_category_enum').create(op.get_bind())
    op.add_column('integration_logs', sa.Column('failure_category', sa.Enum('TIMEOUT', 'VALIDATION', 'AUTH', 'ERP_ERROR', 'UNKNOWN', name='failure_category_enum'), nullable=True))
    op.add_column('integration_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('integration_logs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('integration_logs', sa.Column('provider', sa.String(length=50), server_default='VIVVER', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_logs', 'provider')
    op.drop_column('integration_logs', 'retry_count')
    op.drop_column('integration_logs', 'duration_ms')
    op.drop_column('integration_logs', 'failure_category')
    sa.Enum('TIMEOUT', 'VALIDATION', 'AUTH', 'ERP_ERROR', 'UNKNOWN', name='failure_category_enum').drop(op.get_bind())
    # ### end Alembic commands ###
