"""add_raw_fields_to_inbound_items

Revision ID: efb46aeb9e9c
Revises: f6f49f44cddb
Create Date: 2026-05-13 17:56:25.578016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb46aeb9e9c'
down_revision: Union[str, Sequence[str], None] = 'f6f49f44cddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound_items', sa.Column('raw_product_name', sa.String(length=500), nullable=True))
    op.add_column('inbound_items', sa.Column('raw_manufacturer_name', sa.String(length=500), nullable=True))
    op.add_column('inbound_items', sa.Column('raw_gtin', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound_items', 'raw_gtin')
    op.drop_column('inbound_items', 'raw_manufacturer_name')
    op.drop_column('inbound_items', 'raw_product_name')
    # ### end Alembic commands ###
