"""add_inbound_staging_and_batch_scoping

Revision ID: f6f49f44cddb
Revises: d2a1c62fc854
Create Date: 2026-05-13 17:55:51.834086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f49f44cddb'
down_revision: Union[str, Sequence[str], None] = 'd2a1c62fc854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('sector_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('MANUAL', 'XML_NFE', name='inboundtype'), nullable=False),
    sa.Column('status', sa.Enum('STAGING', 'VALIDATED', 'COMPLETED', 'FAILED', name='inboundstatus'), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_items',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('manufacturer_id', sa.Uuid(), nullable=True),
    sa.Column('batch_number', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), server_default='0.0000', nullable=False),
    sa.Column('is_matched', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['inbound_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory_balances', sa.Column('batch_number', sa.String(length=64), nullable=False))
    op.add_column('inventory_balances', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_inv_balance_lookup'), table_name='inventory_balances')
    op.create_index('ix_inv_balance_lookup', 'inventory_balances', ['product_id', 'unit_id', 'sector_id', 'batch_number'], unique=True)
    op.create_index('ix_inv_balance_expiry', 'inventory_balances', ['expiry_date'], unique=False)
    op.add_column('inventory_movements', sa.Column('batch_number', sa.String(length=64), nullable=True))
    op.add_column('inventory_movements', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_inventory_movements_batch', 'inventory_movements', ['batch_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movements_batch', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'expiry_date')
    op.drop_column('inventory_movements', 'batch_number')
    op.drop_index('ix_inv_balance_expiry', table_name='inventory_balances')
    op.drop_index('ix_inv_balance_lookup', table_name='inventory_balances')
    op.create_index(op.f('ix_inv_balance_lookup'), 'inventory_balances', ['product_id', 'unit_id', 'sector_id'], unique=True)
    op.drop_column('inventory_balances', 'expiry_date')
    op.drop_column('inventory_balances', 'batch_number')
    op.drop_table('inbound_items')
    op.drop_table('inbound_sessions')
    # ### end Alembic commands ###
